### ISSUE TITLE
Style Topbar

### ISSUE THREAD

**Issue by jho44** [Ishnoor-Singh/SolarWebSite#26]
### Problem
Our current topbar is overcrowded. It especially doesn't do well on mobile devices. 
![image](https://user-images.githubusercontent.com/45194378/115193345-e3ae6200-a0a0-11eb-87ab-bc7f1f712fe4.png)
As you can see, buttons get cut off on the sides. Don't worry; we're not asking you to make this responsive.

### Your Task
Replace the Blocks button in the topbar with an Edit button. When Edit is clicked, a dropdown menu should appear with the options "Blocks" and "Members". Those buttons should then lead the user to the edit blocks and edit members pages, respectively. (If the "edit members" page isn't up by the time you get to this issue, just redirect to a dummy page.)

**Comment by sweeneyngo** [comment]
**Summary**
---
- Added dropdown under 'Edit' once authenticated through Login. 
- Dropdown contains buttons for 'Blocks' and 'Members', which are responsive/structurally similar to the other Buttons.
- Clicking them will lead to proper routing pages, with Members (for now) redirecting to a dummy page.
- Reformatted `Topbar.jsx` to organize codebase into smaller, reusable components + class-based CSS. 

**Bugs**
---
- [ ] No animation once rendered, so it looks clunky.
- [ ] After authentication, the edit button doesn't render (requires refreshing to take effect).
